### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jessejr** [adicu/eventum#134]
I made the configurations in Ubuntu using Vagrant, but when running in the browser I get the error "OSError: [Errno 2] No such file or directory".

The following packages had an error message in the system - Could not find any downloads que Satisfy the requirement:
    GnuPGInterface==0.3.2
    apt-xapian-index==0.44
    chardet==2.0.1
    command-not-found==0.2.44
    distribute==0.6.24dev-r0
    language-selector==0.1
    python-apt==0.8.3ubuntu7
    python-debian==0.1.21ubuntu1
    ufw==0.31.1-1
    unattended-upgrades==0.1

The log was generated as follows:
ERROR @ 2015-01-19 18:33:33,198 @ base.py exceptionHandler 24: Uncaught Exception
Traceback (most recent call last):
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/eventum/app/routes/client.py", line 43, in index
    blog_post=blog_post)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/eventum/app/templates/index.html", line 1, in top-level template code
    {% extends "page.html" %}
  File "/var/www/eventum/app/templates/page.html", line 23, in top-level template code
    {% set navbar_items = [('Events', '/events'),
  File "/var/www/eventum/app/templates/base.html", line 4, in top-level template code
    {%- block head -%}
  File "/var/www/eventum/app/templates/base.html", line 54, in block "head"
    {%- block css-%}
  File "/var/www/eventum/app/templates/index.html", line 4, in block "css"
    {{ super() }}
  File "/var/www/eventum/app/templates/page.html", line 7, in block "css"
    {% assets "scss_client" %}
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 181, in _render_assets
    urls = bundle.urls(env=env)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 681, in urls
    urls.extend(bundle._urls(env, extra_filters, *args, **kwargs))
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 643, in _urls
    *args, **kwargs)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 498, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/bundle.py", line 423, in _merge_and_apply
    kwargs=item_data)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/merge.py", line 269, in apply
    return self._wrap_cache(key, func)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/merge.py", line 216, in _wrap_cache
    content = func().getvalue()
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/merge.py", line 249, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/filter/sass.py", line 151, in input
    self._apply_sass(_in, out, os.path.dirname(source_path))
  File "/var/www/eventum/venv/local/lib/python2.7/site-packages/webassets/filter/sass.py", line 132, in _apply_sass
    shell=(os.name == 'nt'))
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jessejr** [comment]
Solved! I installed "sass" and everything worked perfectly.

Installing saas: http://ndever.net/articles/linux/installing-sass-and-compass-ubuntu-1210-1304
